# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-01-27 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='username',
            new_name='email',
        ),
    ]
